#!/bin/sh
set -xa

export PS4='$SECONDS + '
date -u

export DATA=${DATA:-${DATAROOT}/${jobid:?}}
[[ -d $DATA ]] && rm -rf $DATA
mkdir -p $DATA
cd $DATA

#Set PDY and YPDYHHMM to search COMIN/COMOUT for forecast
export PDY=$(date +"%Y%m%d")
export PDYHHMM="$PDY$(date +"%H%M")"

#Set yesterday PDY and YPDYHHMM to search yesterdays COMIN/COMOUT for forecast
export YPDY=$(finddate.sh $PDY d-1)
export YPDYHHMM="$YPDY$(date +"%H%M")"

##############################################
# Define variables/flags
##############################################
export NET=hwm
export RUN=hwm
export model_ver=${hwm_ver}
export KEEPDATA=${KEEPDATA:-NO}

####################################
# Specify Execution Areas
####################################
export FIXhwm=${FIXhwm:-${HOMEhwm}/fix}
export EXEChwm=${EXEChwm:-${HOMEhwm}/exec}
export SORChwm=${SORChwm:-${HOMEhwm}/sorc}
export PARMhwm=${PARMhwm:-${HOMEhwm}/parm}
export USHhwm=${USHhwm:-${HOMEhwm}/ush}

##############################################
# Define COM directorys
##############################################
export COMIN=${COMIN:-$(compath.py ${NET}/${model_ver}/${RUN}.${PDY})}
export COMINy=${COMINy:-$(compath.py ${NET}/${model_ver}/${RUN}.${YPDY})}
export COMINnwges=${COMINnwges:-$COMIN/nwges_${res}_${rescount}}
export COMINnwgesy=${COMINnwgesy:-$COMINy/nwges_${res}_${rescount}}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${PDY})}
export COMOUTy=${COMOUTy:-$(compath.py -o ${NET}/${model_ver}/${RUN}.${YPDY})}
export COMOUTnwges=${COMOUTnwges:-$COMOUT/nwges_${res}_${rescount}}
export COMOUTnwgesy=${COMOUTnwgesy:-$COMOUTy/nwges_${res}_${rescount}}
export COMOUTproj=${COMOUTproj:-$(compath.py ${NET}/${model_ver}/project_files)}

if [ ! -f $COMOUT ] ; then
    mkdir -m 775 -p $COMOUT $COMOUTnwges $COMOUTproj
fi

if [ ! -f $COMOUTy ] ; then
    mkdir -m 775 -p $COMOUTy $COMOUTnwgesy
fi

# Control file determines which modifications are made by model
export OJSON='${OJSON:-hwm_fcst_${res}_${rescount}_p1.json}'
export FCST_CTRL='${FCST_CTRL:-${PARMhwm}/fcst_ctrl}'
export live='${IJSON:-live_${res}_${rescount}_p1.json}'
export daily='${DAILY:-daily_${res}_${rescount}_p1.json}'

##############################################
# Execute the script
##############################################
${HOMEhwm}/scripts/exhwm_forecast.sh
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

cd $DATAROOT
if [ "$KEEPDATA" == "NO" ]; then
    rm -rf $DATA
fi
date
